name: 'mapped/action-semver'
description: 'Establishes a common SEMVER in enviornment variables and version.txt file'
author: 'Mapped <info@mapped.com>'

inputs:
  baseVersion:
    description: 'The base version of this repo. The first version of release. Applied if there is no any release yet. "v" prefix is optional.'
    required: true
  dockerImage:
    description: 'The name of the docker image to produce tags for. If omitted, no docker tags will be produced.'
    required: false
    default: ''
  gitHubToken:
    description: 'The GITHUB_TOKEN value. Required to produce latest tags.'
    required: false
    default: ''
  branchMappings:
    description: 'Used for mapping untagged branches to tag names, such as main:edge.'
    required: false
    default: 'main:edge'
  prereleasePrefix:
    description: 'The <pre-release> prefix on an untagged run.'
    required: false
    default: 'prerelease'
  versionFile:
    description: 'A filename where the full SEMVER and commit SHA will be written. Set to empty string if you do not want a version file to be created.'
    required: false
    default: 'VERSION'
  releasesBranch:
    description: 'Branch where automatic releases should be created. Set to empty string to deactivate releases creation'
    required: false
    default: 'main'
  forcePatchIncrementIfNoChanges:
    description: 'Forces to increment patch if no changes were made since the last release'
    required: false
    default: 'false'
  dockerPlatformSuffix:
    description: 'Adds a suffix to the docker tag to identify the platform that can be referenced by a composit manifest'
    required: false
    default: ''

outputs:
  ver_major:
    description: Major version portion of the SEMVER
  ver_minor:
    description: Minor version portion of the SEMVER
  ver_patch:
    description: Patch version portion of the SEMVER
  ver_preRelease:
    description: Pre-release portion of the SEMVER
  ver_metadata:
    description: Metadata portion of the SEMVER
  ver_buildNumber:
    description: The current build number
  ver_created:
    description: ISO8601 datetime stamp of when the build was run
  ver_tag:
    description: The version tag
  ver_semVer:
    description: The full SEMVER (including any pre-release info and all metadata)
  ver_semVerNoMeta:
    description: The SEMVER without any metadata (including any pre-release info)

  docker_tags:
    description: A list of docker tags that can be passed to docker/build-push-action@v2
  docker_push:
    description: A true/false flag that can be passed to docker/build-push-action@v2
  docker_dtag:
    description: The most deterministic of the tags in docker_tags.

  oci_title:
    description: The org.opencontainers.image.title label
  oci_description:
    description: The org.opencontainers.image.description label
  oci_url:
    description: The org.opencontainers.image.url label
  oci_source:
    description: The org.opencontainers.image.source label
  oci_version:
    description: The org.opencontainers.image.version label
  oci_created:
    description: The org.opencontainers.image.created label
  oci_revision:
    description: The org.opencontainers.image.revision label
  oci_licenses:
    description: The org.opencontainers.image.licenses label
  oci_labels:
    description: The new-line separated list of OCI labels that can be passed to docker/build-push-action@v2

  release_tag:
    description: Release tag. Contains version or empty value if release was not created.

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: target
  color: 'blue'
